{{-- /resources/views/scenario/update.blade.php --}}
@extends('layouts.master')

@section('title')
    Mortgage Payment Calculator
@endsection

@section('form_content')
  <h2>Update Mortgage Scenario Information to Database</h2>
    <!--start of form using POST method -->
    <Form method='POST' action='/scenario/update' id='formUpdate'>
        <!--CSRF protection code -->
        {{ csrf_field() }}
        <!--hidden number input box for loading up the loan scenario using dbrow_id autogenerated by the database-->
        <input type='number' name='dbrow_id' value='{{$scenario->id}}'>
        <!--number input box for loan scenario number maintained by the user-->
        <label for='scenarioNumber'>Loan Scenario Number:</label>
        <input type='number' id='scenarioNumber' step='1' min='1' name='scenarioNumber' value= '{{$scenario->scenario_number}}'><br/>
        <!--text input box for loan scenario name to be maintained by the user for identifying the scenario visually-->
        <label for='scenarioName'>Loan Scenario Name:</label>
        <input type='text' id='scenarioName' name='scenarioName' value= '{{$scenario->scenario_name}}'><br/>
        <!--number input box for loan amount entry -->
        <label for='loan'>Loan Amount:</label>
        <input type='number' id='loan' step='0.01' min='1' name='loan' value= '{{$scenario->loan_amount}}'><br/>
        <!--Reference: Information leveraged to retain data in textboxes
         https://laracasts.com/discuss/channels/laravel/input-data-not-remaining-after-refresh-using-old?page=1-->

        <!--number input box for interest rate entry -->
        <label for='interestRateAnnual'>Interest Rate Annual:</label>
        <input type='number' id='interestRateAnnual' step='0.001' min='1.01' name='interestRateAnnual' value= '{{$scenario->interest_rate_annual}}'><br/>
        <!--option radio buttons for chosing the type of interest rate -->
        <b>Interest Type:</b>
        <label><input type='radio' name='interestType' value='fixed' {{$scenario->interest_type=='fixed' ? 'checked' : ''}}> Fixed</label>
        <label><input type='radio' name='interestType' value='variable' {{$scenario->interest_type=='variable'  ? 'checked' : ''}}> Variable</label><br/>
        <!--Reference: Information leveraged to retain option boxes checked
        https://laracasts.com/discuss/channels/laravel/sex-radio-input-options-old-input-->

        <!--select downdown for selecting the duration of loan in years -->
        <label for='loanDurationYears'>Select loan duration</label>
        <select name='loanDurationYears' id='loanDurationYears'>
          <option value=''> Select one</option>
          <option value='15' {{$scenario->loan_duration_years=='15' ? 'Selected' : ''}} > 15 yrs</option>
          <option value='20' {{$scenario->loan_duration_years=='20' ? 'Selected' : ''}} > 20 yrs</option>
          <option value='25' {{$scenario->loan_duration_years=='25' ? 'Selected' : ''}} > 25 yrs</option>
          <option value='30' {{$scenario->loan_duration_years=='30' ? 'Selected' : ''}} > 30 yrs</option>
          <option value='35' {{$scenario->loan_duration_years=='35' ? 'Selected' : ''}} > 35 yrs</option>
          <option value='40' {{$scenario->loan_duration_years=='40' ? 'Selected' : ''}} > 40 yrs</option>
        </select><br/>
        {{-- --}}

        <!--text read only box for interest rate monthly entry -->
        <label for='interestRateMonthly'>Interest Rate Monthly:</label>
        <input type='number' id='interestRateMonthly' name='interestRateMonthly' value= {{$scenario->interest_rate_monthly}} disabled><br/>
        <!--text read only box for loan duration months -->
        <label for='loanDurationMonthly'>Loan Duration Months:</label>
        <input type='number' id='loanDurationMonthly' name='loanDurationMonthly' value= '{{$scenario->loan_duration_months}}' disabled> <br/>
        <!--text read only box for loan monthly payment -->
        <label for='loanMonthlyPayment'>Loan Monthly Payment:</label>
        <input type='number' id='loanMonthlyPayment' name='loanMonthlyPayment' value= '{{$scenario->loan_monthly_payment}}' disabled><br/>
        <!--text read only box for total interest paid -->
        <label for='interestTotalPaid'>Total Interest Paid:</label>
        <input type='number' id='interestTotalPaid' name='interestTotalPaid' value= '{{$scenario->interest_total_paid}}' disabled><br/>
        <!--text read only box for avg interest rate -->
        <label for='interestRateAvg'>Total Interest Paid:</label>
        <input type='number' id='interestRateAvg' name='interestRateAvg' value= '{{$scenario->interest_rate_average}}' disabled><br/>
        <!--text read only box for total loan cost -->
        <label for='loanTotalCost'>Total Interest Paid:</label>
        <input type='number' id='loanTotalCost' name='loanTotalCost' value= '{{$scenario->loan_total_cost}}' disabled><br/>
        <!--text read only box for total loan payments -->
        <label for='loantotalPayments'>Total Interest Paid:</label>
        <input type='number' id='loanTotalPayments' name='loanTotalPayments' value= '{{$scenario->loan_payments_count}}' disabled><br/>

        <select name='propertySelect' id='propertySelect'>
          <option value='0'>Choose</option>
            @foreach($properties as $properties)
            <option value='{{$properties->prop_id}}' {{ $scenario->property_id == $properties->prop_id ? 'Selected' : '' }}>{{$properties->property_name}}</option>
            @endforeach
        </select></br>

        <!--submit & reset buttons -->
        <input type='submit' name='submit' class='btn btn-primary btn-small' value='save'>
        <input type='button' name='reset' class='btn btn-primary btn-small' onclick="location='./{{$id}}'" value='Reset Form'>
        <!--Reference: Technique for reset button, got ideas from Piazza forum and this website:
        http://www.plus2net.com/html_tutorial/button-linking.php -->
  </form>

@endsection


@section('error_content')
    <!--check for validation errors, if found, display and hald calculations, code leveraged from class lecture notes -->
    <h6>&nbsp;</h6>
    @if(count($errors) > 0)
      <h4>Data entry error found. See below: </h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }} </li>
            @endforeach
            Input values preset to previously saved values.
        </ul>
    @endif
@endsection

@section('mortcalc_content')
    <!--conditional display once GET happens; display of inputs, calculated status, and mortgage payment -->
    <h6>&nbsp;</h6>
    {{-- @if($_POST && count($errors) == 0)
      <hr>
        <div>
          <h3>Mortgage Loan Scenario Saved</h3>
          Scenario Number: {{$scenarioNumber or ''}} <br/>
          Scenario Name: {{$scenarioName or ''}} <br/>
          Loan Amount: ${{$loanDisplay or ''}} <br/>
          Interest Rate (Annual): {{$interestRateDisplay or ''}}% <br/>
          Interest Rate (Monthly): {{$interestRateMonthlyDisplay or ''}}% <br/>
          Interest Type: {{$interestTypeDisplay or ''}} <br/>
          Loan Duration Years: {{$loanDurationDisplay or ''}} yrs <br/>
          Loan Duration Months: {{$loanMonths or ''}} mons <br/>
          Loan Monthly Payment: ${{$monthlyPaymentDisplay or ''}} <br/>
          Total Interest Paid: ${{$interestTotal}} <br/>
          Average Interest Rate (Monthly): {{$interestRateAvg}}% <br/>
          Total Loan Cost: ${{$loanTotalCost}} <br/>
          Number Payments : {{$loanMonths}} <br/>

        </div>
    @endif --}}
@endsection

@section('loancost_content')
    <!--conditional display once GET happens check box is checked; display of loan lifetime cost summary -->
    <h6>&nbsp;</h6>
    {{-- @if(!empty($_GET['show_loanCost']) && $_GET && count($errors) == 0)
      <hr>
        <div>
          <h3>Mortgage Lifetime Cost Summary</h3>
          Loan Amount: ${{$loanDisplay}}<br/>
          Total Interest Paid: ${{$interestTotal}}<br/>
          Average Interest Rate (Monthly): {{$interestRateAvg}}%<br/>
          Total Loan Cost: ${{$loanTotalCost}}<br/>
          Number Payments : {{$loanMonths}}<br/>
          From: {{$array_date[1]}} to {{$array_date[$loanMonths]}}
        </div>
        <input type='button' name='save' class='btn btn-primary btn-small' onclick="parent.location='/scenario/save'" value='Save Scenario'>
    @endif --}}
    <p><a href="/scenario">Mortgage Scenario Landing Page</a></p>
    <p><a href="/index.php">Mortgage Payment Calculator</a></p>
@endsection

@section('amorttbl_content')
    <!--conditional display of mortgage amortization table, code stored on separate php files that has table display logic (soc)-->
    <h6>&nbsp;</h6>
    {{-- @if(!empty($_GET['show_table']) && $_GET && count($errors) == 0)
      <hr>
        <div>
          <h3>Mortgage Amortization Schedule</h3>
          @include('amortTbl');
        </div>
    @endif --}}
@endsection
