{{-- /resources/views/property/addfeatures.blade.php --}}
{{-- blade view to add property features using table joins --}}

@extends('layouts.master')

@section('title')
  Real Estate Property Information
@endsection

@section('form_content')
  <h2>Save a new Real Estate Property Information in the Database</h2>
  <!--start of form -->
  <Form method='POST' action='/property/addfeatures' id='formAddFeatures'>
        <!--croos site attack prevention -->
        {{ csrf_field() }}
        <!--hidden number input box for loading up the porperty using id autogenerated by the database-->
        <input type='hidden' name='id' value='{{$properties->id}}'><br/>
        <!--text input box for Property number -->
        <label for='propertyNumber'>Property MLS Number:</label>
        <input type='number' id='propertyNumber' name='propertyNumber' value= '{{$properties->property_number}}' disabled><br/>
        <!--text input box for Property name to be maintained by the user for identifying easily-->
        <label for='propertyName'>Property Name:</label>
        <input type='text' id='propertyName' name='propertyName' value= '{{$properties->property_name}}' disabled><br/>


        <label>Existing Key Features</label>
        <ul id='features'>
            @forelse($featureSelected as $featureSelect)
                <li>{{ $featureSelect->feature_name }}</li>
            @empty
                {{'No features found for this property'}}
            @endforelse
        </ul>

        <!--select dropdown populated from database & eloquent model -->
        <!--only those features are available that are not already specified for the property -->
        <label for='featureSelect'>Select a Key Feature to Add</label><br/>
        <select name='featureSelect' id='featureSelect'>
          <option value='0'>Choose</option>
            @foreach($features as $features)
                <option value='{{$features->id}}'> {{$features->feature_name}}</option>
            @endforeach
        </select><br/>

        <!--submit & reset buttons -->
        <input type='submit' name='submit' class='btn btn-primary btn-small' value='save'>

  </form>

@endsection


@section('error_content')
    <!--check for validation errors, if found, display and hald calculations, code leveraged from class lecture notes -->
    <h6>&nbsp;</h6>
    @if(count($errors) > 0)
      <h4>Data entry error found. See below: </h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }} </li>
            @endforeach
        </ul>
    @endif
@endsection

@section('mortcalc_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection

@section('loancost_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection

@section('amorttbl_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection
