{{-- /resources/views/index.blade.php --}}
@extends('layouts.master')

@section('title')
  Real Estate Property Information
@endsection

@section('form_content')
  <h2>Save a new Real Estate Property Information in the Database</h2>
  <!--start of form -->
  <Form method='POST' action='/property/addfeatures' id='formAddFeatures'>
        {{ csrf_field() }}
        <!--hidden number input box for loading up the loan scenario using id autogenerated by the database-->
        <label for='id'>Property ID:</label>
        <input type='number' name='id' value='{{$properties->id}}'><br/>
        <!--text input box for loan scenario number -->
        <label for='propertyNumber'>Property MLS Number:</label>
        <input type='number' id='propertyNumber' name='propertyNumber' value= '{{$properties->property_number}}' ><br/>
        <!--text input box for loan scenario name to be maintained by the user for identifying the scenario visually-->
        <label for='propertyName'>Property Name:</label>
        <input type='text' id='propertyName' name='propertyName' value= '{{$properties->property_name}}' ><br/>
        <!--text read only box for Property Address -->

        {{-- <label>Features</label>
          <ul id='features'>
              @foreach($features as $features)
                  <li><input
                      type='checkbox'
                      value='{{ $features->id }}'
                      id='feature_{{ $features->id }}'
                      name='features[]'
                      {{ $property->feature_name ?  'CHECKED' : '' }}
                  >&nbsp;
                  <label for='feature_{{ $features->id }}'>{{ $features->feature_name }}</label></li>
              @endforeach --}}

{{-- {{ (in_array($name, $tagsForThisBook)) ? 'CHECKED' : '' }} --}}


              {{-- <label>Key Features</label>
              <ul id='features2'>
                  @foreach($features as $features)
                      <li>{{ $features->id }}, {{ $features->feature_number }}, {{ $features->feature_name }} </li>
                  @endforeach
              </ul> --}}

              <label>Key Features</label>
              <ul id='features3'>
                  @foreach($featureSelected as $featureSelected)
                      <li>{{ $featureSelected->id }},
                        {{ $featureSelected->feature_name }},
                       </li>
                  @endforeach
              </ul>

              <select name='featureSelect' id='featureSelect'>
                <option value='0'>Choose</option>
                  @foreach($features as $features)
                  <option value='{{$features->id}}'> {{$features->feature_name}}</option>
                  @endforeach
              </select></br>
              {{-- {{ $scenario->property_id == $properties->id ? 'Selected' : '' }} --}}

              {{-- <label>Features</label>
                <ul id='features'>
                    @foreach($features as $features)
                        <li><input
                            type='checkbox'
                            value='{{ $features->id }}'
                            id='feature_{{ $features->id }}'
                            name='features[]'
                            {{ $features->id }}
                            {{ $features->id == $propertyfeatures->feature_id ?  'CHECKED' : '' }}
                        >&nbsp;
                        <label for='feature_{{ $features->id }}'>{{ $features->feature_name }}</label></li>
                    @endforeach --}}





        <!--submit & reset buttons -->
        <input type='submit' name='submit' class='btn btn-primary btn-small' value='save'>
        <input type='button' name='reset' class='btn btn-primary btn-small' onclick="location='./{{$id}}'" value='Reset Form'>
        <!--Reference: Technique for reset button, got ideas from Piazza forum and this website:
        http://www.plus2net.com/html_tutorial/button-linking.php -->
  </form>

@endsection


@section('error_content')
    <!--check for validation errors, if found, display and hald calculations, code leveraged from class lecture notes -->
    <h6>&nbsp;</h6>
    {{-- @if(count($errors) > 0)
      <h4>Data entry error found. See below: </h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }} </li>
            @endforeach
            Input values preset to previously entered values.
            Please submit form again with preset values or with updated values.
        </ul>
    @endif --}}
@endsection

@section('mortcalc_content')
    <!--conditional display once GET happens; display of inputs, calculated status, and mortgage payment -->
    <h6>&nbsp;</h6>
    {{-- @if($_POST && count($errors) == 0)
      <hr>
        <div>
          <h3>Real Estate Property Information Saved</h3>
          Property Number: {{$properties->property_number or ''}} <br/>
          Property Name: {{$properties->property_name or ''}} <br/>
          Property Address: {{$properties->property_address or ''}} <br/>
          Property Type: {{$properties->property_type or ''}} <br/>
          Property Size: {{$properties->property_size or ''}}% <br/>
          Property Living Space (sqft): {{$properties->living_area or ''}} <br/>
          Property Lot Size (acres): {{$properties->lot_size or ''}} yrs <br/>
          Year Built: {{$properties->year_built or ''}} mons <br/>
          Property Sale Price: ${{$properties->sale_price or ''}} <br/>
          Property Tax Rate: {{$properties->tax_rate}}% <br/>
          Property Yearly HOA: ${{$properties->hoa_yearly}} <br/>

        </div>
    @endif --}}
@endsection

@section('loancost_content')
    <!--conditional display once GET happens check box is checked; display of loan lifetime cost summary -->
    <h6>&nbsp;</h6>
    {{-- @if(!empty($_GET['show_loanCost']) && $_GET && count($errors) == 0)
      <hr>
        <div>
          <h3>Mortgage Lifetime Cost Summary</h3>
          Loan Amount: ${{$loanDisplay}}<br/>
          Total Interest Paid: ${{$interestTotal}}<br/>
          Average Interest Rate (Monthly): {{$interestRateAvg}}%<br/>
          Total Loan Cost: ${{$loanTotalCost}}<br/>
          Number Payments : {{$loanMonths}}<br/>
          From: {{$array_date[1]}} to {{$array_date[$loanMonths]}}
        </div>
        <input type='button' name='save' class='btn btn-primary btn-small' onclick="parent.location='/scenario/save'" value='Save Scenario'>
    @endif --}}
    <p><a href="/property">Real Estate Property Management Landing Page</a></p>
@endsection

@section('amorttbl_content')
    <!--conditional display of mortgage amortization table, code stored on separate php files that has table display logic (soc)-->
    <h6>&nbsp;</h6>
    {{-- @if(!empty($_GET['show_table']) && $_GET && count($errors) == 0)
      <hr>
        <div>
          <h3>Mortgage Amortization Schedule</h3>
          @include('amortTbl');
        </div>
    @endif --}}
@endsection
