{{-- /resources/views/property/viewfeatures.blade.php --}}
{{-- blade view to show property features using table joins --}}

@extends('layouts.master')

@section('title')
  Real Estate Property Feastures Information
@endsection

@section('form_content')
  <h2>View Real Estate Property Feature Information from the Database</h2>
  <!--start of form -->
  <Form method='GET' action='/property/viewfeatures' id='formViewFeatures'>
        <!--hidden number input box for loading up the property using id autogenerated by the database-->
        <input type='hidden' name='id' value='{{$properties->id}}'><br/>
        <!--number input box for property mls number -->
        <label for='propertyNumber'>Property MLS Number:</label>
        <input type='number' id='propertyNumber' name='propertyNumber' value= '{{$properties->property_number}}' disabled><br/>
        <!--text input box for property friendly name to be maintained by the user for identifying the property visually-->
        <label for='propertyName'>Property Name:</label>
        <input type='text' id='propertyName' name='propertyName' value= '{{$properties->property_name}}' disabled><br/>


        <!-- feature ul list using forelse loop to extract property features using pivot table -->
        <label>Key Features</label>
        <ul id='features'>
            @forelse($featureSelected as $featureSelect)
                <li>{{ $featureSelect->feature_name }}</li>
            @empty
                {{'No features found for this property'}}
            @endforelse
        </ul>
        {{-- Reference: Leveraged class lecture notes for extracting info using pivot table -> https://github.com/susanBuck/foobooks/blob/master/resources/views/books/edit.blade.php --}}
        {{-- Reference: Leveraged stackoverflow for using @forelse loop -> http://stackoverflow.com/questions/32652818/laravel-blade-check-empty-foreach --}}

  </form>

@endsection


@section('error_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
      <h6>&nbsp;</h6>
@endsection

@section('mortcalc_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
      <h6>&nbsp;</h6>
@endsection

@section('loancost_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
      <h6>&nbsp;</h6>
@endsection

@section('amorttbl_content')
  <!--blade template placeholder section, satisfies html validator requirements -->
      <h6>&nbsp;</h6>
@endsection
