{{-- /resources/views/property/view.blade.php --}}
{{-- blade view a single real estate property listing with features using join pivot table --}}

@extends('layouts.master')

@section('title')
  Real Estate Property Information
@endsection

@section('form_content')
  <h2>View a Real Estate Property Information saved in the Database</h2>
    <!--start of form using POST method -->
    <Form method='GET' action='/property/view' id='formView'>
        <h3> Real Estate Property Information </h3>
        <!--hidden number input box for loading up the property info using id autogenerated by the database-->
        <input type='hidden' name='id' value='{{$properties->property_number}}' disabled>
        <!--number input box for the property mls number maintained by the user-->
        <label for='propertyNumber'>Property MLS Number:</label>
        <input type='number' id='propertyNumber' name='propertyNumber' value= '{{$properties->property_number}}' disabled><br/>
        <!--text input box for property name to be maintained by the user for identifying visually-->
        <label for='propertyName'>Property Name:</label>
        <input type='text' id='propertyName' name='propertyName' value= '{{$properties->property_name}}' disabled><br/>
        <!--text read only box for Property Address -->
        <label for='propertyAddress'>Property Address:</label>
        <input type='text' id='propertyAddress' name='propertyAddress' value= '{{$properties->property_address}}' size='50' disabled><br/>
        <!--text read only box for Property Type -->
        <label for='propertyType'>Property Type: </label>
        <input type='text' id='propertyType' name='propertyType' value= '{{$properties->property_type}}' disabled><br/>
        <!--text read only box for Property Size -->
        <label for='propertySize'>Property Size: </label>
        <input type='text' id='propertySize' name='propertySize' value= '{{$properties->property_size}}' disabled><br/>
        <!--text read only box for Property Living Space -->
        <label for='livingArea'>Property Living Space (sqft): </label>
        <input type='text' id='livingArea' name='livingArea' value= '{{$properties->living_area}}' disabled><br/>
        <!--text read only box for Property Lot Size -->
        <label for='lotSize'>Property Lot Size (acres): </label>
        <input type='text' id='lotSize' name='lotSize' value= '{{$properties->lot_size}}' disabled><br/>
        <!--text read only box for Property Year Built -->
        <label for='yearBuilt'>Property Year Built: </label>
        <input type='text' id='yearBuilt' name='yearBuilt' value= '{{$properties->year_built}}' disabled><br/>
        <!--text read only box for Property Sale Price -->
        <label for='salePrice'>Property Sale Price ($): </label>
        <input type='text' id='salePrice' name='salePrice' value= '{{$properties->sale_price}}' disabled><br/>
        <!--text read only box for Property Tax Rate -->
        <label for='taxRate'>Property Tax Rate (%): </label>
        <input type='text' id='taxRate' name='taxRate' value= '{{$properties->tax_rate}}' disabled><br/>
        <!--text read only box for Property Yearly HOA -->
        <label for='hoaYearly'>Property Yearly HOA ($): </label>
        <input type='text' id='hoaYearly' name='hoaYearly' value= '{{$properties->hoa_yearly}}' disabled><br/>

        <!-- feature ul list using forelse loop to extract property features using pivot table -->
        <label>Key Features</label>
        <ul id='features'>
            @forelse($features as $feature)
                <li>{{ $feature->feature_name }}</li>
            @empty
                {{'No features found for this property'}}
            @endforelse
        </ul>
        {{-- Reference: Leveraged class lecture notes for extracting info using pivot table -> https://github.com/susanBuck/foobooks/blob/master/resources/views/books/edit.blade.php --}}
        {{-- Reference: Leveraged stackoverflow for using @forelse loop -> http://stackoverflow.com/questions/32652818/laravel-blade-check-empty-foreach --}}

  </form>

@endsection


@section('error_content')
    <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection

@section('mortcalc_content')
    <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection

@section('loancost_content')
    <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection

@section('amorttbl_content')
    <!--blade template placeholder section, satisfies html validator requirements -->
    <h6>&nbsp;</h6>
@endsection
